package com.aurionpro.studentmanagement.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents a course offered within an academic department.
 * This entity is mapped to the "courses" table in the database.
 */
@Entity
@Table(name = "courses")
@Getter
@Setter
@Schema(description = "Represents a course offered by a department.")
public class Course {

    /**
     * The unique identifier for the course.
     * This is the primary key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Auto-generated unique database identifier.", example = "101")
    private Long id;

    /**
     * The official name of the course. This field cannot be null.
     */
    @Column(name = "name", nullable = false)
    @Schema(description = "The name of the course.", example = "Data Structures and Algorithms")
    private String name;

    /**
     * A detailed description of the course, outlining its content and objectives.
     */
    @Column(name = "description")
    @Schema(description = "A brief description of the course content.")
    private String description;

    /**
     * The department that offers this course. This establishes a many-to-one relationship,
     * as many courses can belong to a single department. This field cannot be null.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "department_id", nullable = false)
    @Schema(description = "The department that offers this course.")
    private Department department;

    /**
     * A flag indicating whether the course's record is active.
     * Used for soft-deleting records instead of permanent deletion. Defaults to true.
     */
    @Column(name = "is_active", nullable = false)
    @Schema(description = "Indicates if the course record is active.", example = "true")
    private boolean isActive = true;
}