package com.aurionpro.studentmanagement.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents an academic department within the institution.
 * Each department has a unique name and can offer multiple courses.
 * This entity is mapped to the "departments" table.
 */
@Entity
@Table(name = "departments")
@Getter
@Setter
@Schema(description = "Represents an academic department in the institution.")
public class Department {

    /**
     * The unique identifier for the department.
     * This is the primary key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Auto-generated unique database identifier.", example = "1")
    private Long id;

    /**
     * The name of the department. This value must be unique and cannot be null,
     * serving as a natural key.
     */
    @Column(name = "name", nullable = false, unique = true)
    @Schema(description = "The name of the department.", example = "COMPUTER_SCIENCE")
    private String name;
}