package com.aurionpro.studentmanagement.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.HashSet;
import java.util.Set;

/**
 * Represents a student enrolled in the institution.
 * This entity contains personal details, academic information, and metadata.
 * It is mapped to the "students" table and uses JPA Auditing for tracking creation
 * and update timestamps.
 */
@Entity
@Table(name = "students")
@Getter
@Setter
@EntityListeners(AuditingEntityListener.class) // Enable JPA Auditing
@Schema(description = "Represents a student enrolled in the institution.")
public class Student {

    /**
     * The internal unique identifier for the student record.
     * This is the primary key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Auto-generated unique database identifier.", example = "1")
    private Long id;

    /**
     * The business identifier for the student, which must be unique across the system.
     * This is a distinct identifier used for external-facing operations.
     */
    @Column(name = "student_id", nullable = false, unique = true, length = 100)
    @Schema(description = "Unique business ID of the student.", example = "S001")
    private String studentId;

    /**
     * The first name of the student. This field cannot be null.
     */
    @Column(name = "first_name", nullable = false)
    @Schema(description = "First name of the student.", example = "Nilesh")
    private String firstName;

    /**
     * The last name of the student. This field cannot be null.
     */
    @Column(name = "last_name", nullable = false)
    @Schema(description = "Last name of the student.", example = "Gawli")
    private String lastName;

    /**
     * The email address of the student, which must be unique.
     * This field is used for communication and identification.
     */
    @Column(name = "email", nullable = false, unique = true)
    @Schema(description = "Email address of the student.", example = "nilesh.gawli@example.com")
    private String email;

    /**
     * The department to which the student is assigned. This creates a many-to-one relationship,
     * where many students can belong to a single department.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "department_id", nullable = false)
    @Schema(description = "The department to which the student is assigned.")
    private Department department;

    /**
     * The set of courses in which the student is currently enrolled.
     * This establishes a many-to-many relationship, managed through a join table
     * named "student_courses".
     */
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "student_courses",
            joinColumns = @JoinColumn(name = "student_id"),
            inverseJoinColumns = @JoinColumn(name = "course_id")
    )
    @Schema(description = "The set of courses in which the student is enrolled.")
    private Set<Course> courses = new HashSet<>();

    /**
     * A flag indicating whether the student's record is active.
     * Used for soft-deleting records instead of permanent deletion. Defaults to true.
     */
    @Column(name = "is_active", nullable = false)
    @Schema(description = "Indicates if the student record is active.", example = "true")
    private boolean isActive = true;

    /**
     * The timestamp when the student record was created.
     * This is automatically managed by JPA Auditing and is not updatable.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    @Schema(description = "UTC timestamp when the student record was created.")
    private Instant createdAt;

    /**
     * The timestamp when the student record was last updated.
     * This is automatically managed by JPA Auditing.
     */
    @LastModifiedDate
    @Column(name = "updated_at")
    @Schema(description = "UTC timestamp when the student record was last updated.")
    private Instant updatedAt;
}